name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build with Node 20 so Angular is happy
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - run: npm ci
      - run: npx ng build -c production

      # Upload the built artifacts (no Oryx build)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SMOKE_0A63C1910 }}
          action: upload
          app_location: "/"                                   # repo root
          app_artifact_location: "dist/My-first-angular-app"  # <-- use this when skip_app_build=true
          skip_app_build: true
          api_location: ""            # no Functions
          data_api_location: ""       # avoid default 'swa-db-connections'
